from .cat import *
from .ls import *
from .lsl import *
from .wc import *
from .tail import *
from .rm import *
from .rmdir import *
from .pwd import *
from .mkdir import *
from .cd import *
from .mv import *
from .cp import *
from .lsa import *
from .less import *
from .head import *
from .grep import *
from .exit import *